### ISSUE TITLE
request.onload

### ISSUE THREAD

**Issue by KoopReynders** [marchessing/frontendvoordesigners#11]
https://github.com/marchessing/frontendvoordesigners/blob/88806f44223534104b7261070be2e038022f9375/Opdracht%203/V3/script.js#L12

Wat gebeurt hier? Wat is de `request.onload` ?

Het valt me op dat je helemaal nog geen console.log functies in jee script gebruikt. 
Dat heb je nu echt nodig. Dan kun je in de console van de inspector ook zien wat er gebeurt. 
Na het laden van de json data zou een console.log doen om te zien welke data er geladen wordt. 
dus: 

```
request.onload = function() {
  var superHeroes = request.response;
  console.log("superHeroes",superHeroes);
```

Wat zie je dan in je console?

**Comment by marchessing** [comment]
Met deze functie roep je de JSON data op.

Waarna je met de functies populateHeader en showHeroes de content toont in HTML tags.
