### ISSUE TITLE
<meta name=viewport>

### ISSUE THREAD

**Issue by KoopReynders** [marchessing/frontendvoordesigners#14]
https://github.com/marchessing/frontendvoordesigners/blob/5f5a1b1dc76365346ca6b6d9ae33602754762013/Opdracht%203/V4/index.html#L5

Je bent de viewport meta vergeten in de html
`<meta name=viewport content="width=device-width, initial-scale=1">
`

Die heb je nodig dat ook in kleine devices de layout goed gerenderd wordt. Ik kwam erachter toen ik je website aan het debuggen was in Chrome, en ik in de 'responsive' mode een halve website zag.

**Comment by KoopReynders** [comment]
Je hebt nu 2 dingen te doen. 
Ten eerste moet je de films netjes tonen. Ik zou er kaartjes van maken. Waarbij een images goed in beeld past, en de titel en de short-plot ook in beeld staan.  Dat het er netjes uit ziet. Zet eerst maar eens die 6 films netjes naast elkaar.  

Dan de container met overflow: hidden goed zetten en de buttons plaatsen. 

Daarna moet je het script dat je voor je vorige carousel hebt gemaakt, in dit script zetten. Een beetje aanpassen aan de html die je hebt. 
Ik zou niet alleenza maar het script erbij zetten. Er gebeurt nu wel wat, maar het is niet helemaal duidelijk wat er wel/niet beweegt. Beter is dus je oude code stap voor stap toe te voegen, en aan te passen aan je nieuwe vormgeving.

**Comment by marchessing** [comment]
Ik weet even niet hoe ik die nodelist moet vinden. Ik kom elke keer op 0 uit. Hij vindt de articles die ik inlaad niet. Wat moet ik doen zodat hij deze vindt. 

Of moet ik die add.eventlistener in mijn for loop zetten? Nee toch?

**Comment by KoopReynders** [comment]
Kun je een issue aanmaken en verwijzen naar de code waar het over gaat?

**Comment by marchessing** [comment]
Hi Koop,

Ik heb het gefixt en de code werkt! 

Go check it out. 

https://github.com/marchessing/frontendvoordesigners/tree/master/Opdracht%203/V4 <https://github.com/marchessing/frontendvoordesigners/tree/master/Opdracht%203/V4>

Groetjes,

Marc Hessing

**Comment by KoopReynders** [comment]
Dat ziet er goed uit Marc !

Data geladen? top !
Carousel? Jawel !
2 interacties? Ook !


ok, nog 1 ding …
Het valt me op dat de carousel het beter doet met de pijltjes dan met de button.
Ik je javascript zie ik dat de code bij de onkeydown iets anders is dan de click functie.

Kun je 1 functie maken die je zowel voor de button click als de keydown kan aanroepen?


Koop


On 20 Dec 2018, at 14:26, marchessing <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Koop,

Ik heb het gefixt en de code werkt!

Go check it out.

https://github.com/marchessing/frontendvoordesigners/tree/master/Opdracht%203/V4 <https://github.com/marchessing/frontendvoordesigners/tree/master/Opdracht%203/V4>

Groetjes,

Marc Hessing

**Comment by marchessing** [comment]
ja dit had ik dus vorige keer al geprobeerd en kwam er niet helemaal uit hoe en wat. 

Ik ga het gewoon nog een keer proberen.

Ps: dit is al wel voldoende dus (A)?

gr,

Marc

**Comment by KoopReynders** [comment]
Nog even mooie code
En een readme waarin je de code (en interface) uitlegd, en ja het is vdoende!

Ik zou de code pakken die je gebruikt bij de keydown en daar  functie van maken (of twee). En van de buttons en van de keydown die aanroepen. Snep?


On 20 Dec 2018, at 15:07, marchessing <notifications@github.com<mailto:notifications@github.com>> wrote:

ja dit had ik dus vorige keer al geprobeerd en kwam er niet helemaal uit hoe en wat.

Ik ga het gewoon nog een keer proberen.

Ps: dit is al wel voldoende dus (A)?

gr,

Marc
