### ISSUE TITLE
Carousel 

### ISSUE THREAD

**Issue by KoopReynders** [marchessing/frontendvoordesigners#2]
https://github.com/marchessing/frontendvoordesigners/blob/58cd2b6f1a23af9670af7f3b39f0330fc1ecf0b2/Opdracht2/v1/script.js#L16

Ik zie dat je alle img's hebt geselecteerd en ze een andere 'left' waarde wil geven.

Wat is nu je plan voor de carousel? Ik dacht dat je de section waar de img's in zitten wilde bewegen? Zoals we dat hebben getekend. Dat is iets makkelijker. 
Of wil je de img's stuk voor stuk laten bewegen? Dat is denk ik iets lastiger. Want dan moet je alle img's bij elke klik een andere class geven. Een andere oplossing kan zijn dat je alle plaatje buiten beeld zet, en dat je ze om de beurt op left=0 zet, dan ze over elkaar heen worden gezet.Snap je? Maar zo hebben we dat gister niet getekend. (kan er wel leuk uitzien) 

Volgens mij moet je eerst bepalen wat voor carousel je wil maken. 

Daarna kun je verschillende classes aanmaken met allemaal andere 'left' waarde. En dan moet je die om de beurt aan een element toevoegen. De crux is dan dat je moet weten welke plaatje zichtbaar moet zijn. Daar moet je een 'counter' voor bijhouden in javascript. Als de counter 1 is, dan moet de eerste img zichtbaar worden, als de counter 2 is dan ... enzovoort.

**Comment by marchessing** [comment]
Ja dit is top feedback hier kan ik wat mee. Ik heb inderdaad de tekening een beetje verkeerd begrepen dan.

Ik zat zelf ook te denken aan een counter. Nu nog even kijken hoe ik die ga toepassen. 

thanks!
