### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by KoopReynders** [marchessing/frontendvoordesigners#6]
https://github.com/marchessing/frontendvoordesigners/blob/b81c1219408683be60ba18b2270af3de88f86b65/Opdracht%203/V1/index.html#L38

Ik zou de buttons niet in dezelfde `section` stoppen als de plaatjes. Die plaatjes ga je zometeen bewegen, en dan gaan de buttons ook mee !
beter is onder de `section` een `nav` met de buttons?

**Comment by marchessing** [comment]
Ik wil het div.frame dus gaan bewegen en toch niet de section.container?

**Comment by KoopReynders** [comment]
Oh, misschien heb ik dit niet goed gezien?
