### ISSUE TITLE
counter

### ISSUE THREAD

**Issue by KoopReynders** [marchessing/frontendvoordesigners#7]
https://github.com/marchessing/frontendvoordesigners/blob/b81c1219408683be60ba18b2270af3de88f86b65/Opdracht%203/V1/script.js#L14

Hier maak je een foutje. Je wil de counter met 1 ophogen als je op de button next klikt, right?
Je doet nu `counter +1` 
Wat betekent dat? 

Niks ! haha

Je bedoelt waarschijnlijk:
`counter += 1;`
En dat is een korte notatie voor:
`counter = counter + 1;`

Doe dat maar eens en `console.log` dat in de click-eventlistener. 
En? Bingo !
Nu verder naar de switch...

**Comment by marchessing** [comment]
Yes check. Thanks! Ga hem nu ook aanmaken voor de -1
