### ISSUE TITLE
switch

### ISSUE THREAD

**Issue by KoopReynders** [marchessing/frontendvoordesigners#8]
https://github.com/marchessing/frontendvoordesigners/blob/b81c1219408683be60ba18b2270af3de88f86b65/Opdracht%203/V1/script.js#L22

Na een button klik wordt de counter aangepast. 
Daarna wil je dat de carousel naar het bijhorende plaatje 'beweegt'.
Dat heb je met een switch opgelost. 

Hoe weet je code nu dat het de switch moet aanroepen?
Zodat de code wordt uitgevoerd?
De switch staat daar nu 'gewoon'. 
Een beetje te zijn. 

Hoe kun je de switch aanroepen nadat je op een button hebt geklikt?

Wat gebeurt er als je een console.log in de switch zet?
```
switch (counter) {
	console.log("we hebben een switch")
	case 0:
		etc ...
```

**Comment by marchessing** [comment]
Via de console.log krijg ik de volgende error:

Uncaught SyntaxError: Unexpected identifier

**Comment by marchessing** [comment]
ik moet een function schrijven die de switch activeert lijkt mij.
