### ISSUE TITLE
Keydown functie

### ISSUE THREAD

**Issue by KoopReynders** [marchessing/frontendvoordesigners#9]
https://github.com/marchessing/frontendvoordesigners/blob/1a3cbcc6f1964dcf8c0673c3b9a367979bb3f9c7/Opdracht%203/V1/script.js#L61

Hier staat je script voor wat er moet gebeuren als je op een key drukt.
Weer met die switch. Goed zo.

Je schrijft “Alleen werkt de function clearclasses niet meer volledig?”
Heb je dat met de inspector ontdekt?
En heb je met console.log gechecked of de verschillende stappen van je code goed worden uitgevoerd?

**Comment by marchessing** [comment]
Ja ik heb via de console.log gezien dat het toevoegen van de correcte classes werkt via de arrows.

Alleen worden de classes niet verwijderd wanneer je nog een keer op de arrow drukt. Hierdoor komen er meerdere classes en kan je niet terug in de volgorde. 

Dit probleem hadden we ook met de buttons eerst. Dit had jij toen opgelost met de clearclasses functie. Deze werkt nu dus niet meer correct.

**Comment by KoopReynders** [comment]
Is dat probleem hetzelfde met de arrow-keys als met de buttons?
Zo ja dan is er iets met de clear-functie
Zo nee dan is er iets met de key-down functie...

**Comment by marchessing** [comment]
YEHESS ik heb de arrows gefixt. met een:

if else statement om te kijken of het arrow left (37) of arrow right (39) is.

En dan in de if else heb ik een switch gedaan om zo de classes toe te voegen. Weet niet of het de juiste manier is, maar het werkt.

**Comment by KoopReynders** [comment]
Ik zie best veel dezelfde code op verschillende plekker.  Bv de next button en keydown rechts. Daar gebeurt eigenlijk hetzelfde. Zou je dat ook anders kunnen oplossen?
